#!/bin/bash

VESSHEL=$(realpath $(dirname "$0"))
PROJ="$1"
FRAGS=$(echo $PROJ | sed 's/\./ /g')

# make a clean temp directory
TMP=$(mktemp -d)

$VESSHEL/pkg $PROJ $TMP

# build docker image
cd $TMP
docker build --build-arg "user=$(whoami)" -t "$PROJ" . | $VESSHEL/piper
cd /
rm -rf $TMP
