#!/bin/bash

VESSHEL=$(realpath $(dirname "$0"))
PROJ="$1"
OUT="$2"
FRAGS=$(echo $PROJ | sed 's/\./ /g')

touch $OUT/Dockerfile.root $OUT/Dockerfile.user

for x in $FRAGS; do
  # look for the fragment in ~ and $VESSHEL/
  if [ -d ~/$x ]; then
    x=~/$x
  elif [ -d $VESSHEL/$x ]; then
    x=$VESSHEL/$x
  else
    echo "Unable to find fragment '$x'"
    exit
  fi

  # copy all the extra files
  cp -r $x/* $OUT/

  # add the root piece
  echo "#### $x/root" >> $OUT/Dockerfile.root
  cat "$x/root" >> $OUT/Dockerfile.root
  echo >> $OUT/Dockerfile.root

  # add the user piece
  echo "#### $x/user" >> $OUT/Dockerfile.user
  cat "$x/user" >> $OUT/Dockerfile.user
  echo >> $OUT/Dockerfile.user
done

# join all the root and user pieces
cat $OUT/Dockerfile.root $OUT/Dockerfile.user > $OUT/Dockerfile
rm $OUT/Dockerfile.root $OUT/Dockerfile.user
